### ISSUE TITLE
Reference server error

### ISSUE THREAD

**Issue by ApuscasiteiSilviu** [sergiuiacob1/Timetable-Maker#5]
```
ReferenceError: getResourceById is not defined
            at updateResourceRoute (/application/app/resource_routes.js:46:5)
            at Layer.handle [as handle_request] (/application/node_modules/express/lib/router/layer.js:95:5)
            at next (/application/node_modules/express/lib/router/route.js:137:13)
            at Route.dispatch (/application/node_modules/express/lib/router/route.js:112:3)
            at Layer.handle [as handle_request] (/application/node_modules/express/lib/router/layer.js:95:5)
            at /application/node_modules/express/lib/router/index.js:281:22
            at Function.process_params (/application/node_modules/express/lib/router/index.js:335:12)
            at next (/application/node_modules/express/lib/router/index.js:275:10)
            at logger (/application/node_modules/morgan/index.js:144:5)
            at Layer.handle [as handle_request] (/application/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by MihaiBojescu** [comment]
Fixed in pull request #7
